product: mezzanine: shiratech cam 1
96boards/website pull request #1343
Opened 2020-12-14 11:37 UTC by ric96

Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

2020-12-14 11:39 UTC, ric96 commented
Broken links may be fixed by merging the doc pr: https://github.com/96boards/documentation/pull/915

2020-12-14 11:47 UTC, sgermanserrano approved these changes
LGTM

2021-02-10 13:32 UTC, kylekirkby requested changes

2021-02-10 13:32 UTC, kylekirkby commented on _product/mezzanine/shiratech-cam1/README.md
> +tab_menu:
This should be `sticky_tab_bar`

2021-02-21 12:52 UTC, kylekirkby requested changes

2021-02-21 12:52 UTC, kylekirkby commented on _product/mezzanine/shiratech-cam1/README.md
> +  - tab_title: Shiratech Camera 1 Mezzanine
`tab_title` needs to be `title` and `tab_link` should be `url`.

2021-02-22 09:01 UTC, kylekirkby approved these changes

2021-02-22 09:09 UTC, merged